// Caption languages. Codes are full Azure locale identifiers, passed straight
// through to the fast-transcription API. This is a broad, practical subset of
// Azure's 100+ supported locales (the long tail can be added on request).
export const LANGUAGES = [
	{ code: "en-US", name: "English (US)" },
	{ code: "en-GB", name: "English (UK)" },
	{ code: "en-AU", name: "English (Australia)" },
	{ code: "en-IN", name: "English (India)" },
	{ code: "es-ES", name: "Spanish (Spain)" },
	{ code: "es-MX", name: "Spanish (Mexico)" },
	{ code: "fr-FR", name: "French" },
	{ code: "fr-CA", name: "French (Canada)" },
	{ code: "de-DE", name: "German" },
	{ code: "it-IT", name: "Italian" },
	{ code: "pt-BR", name: "Portuguese (Brazil)" },
	{ code: "pt-PT", name: "Portuguese (Portugal)" },
	{ code: "ru-RU", name: "Russian" },
	{ code: "ja-JP", name: "Japanese" },
	{ code: "zh-CN", name: "Chinese (Mandarin)" },
	{ code: "zh-HK", name: "Chinese (Cantonese)" },
	{ code: "zh-TW", name: "Chinese (Taiwan)" },
	{ code: "ko-KR", name: "Korean" },
	{ code: "nl-NL", name: "Dutch" },
	{ code: "pl-PL", name: "Polish" },
	{ code: "tr-TR", name: "Turkish" },
	{ code: "ar-EG", name: "Arabic (Egypt)" },
	{ code: "ar-SA", name: "Arabic (Saudi Arabia)" },
	{ code: "hi-IN", name: "Hindi" },
	{ code: "sv-SE", name: "Swedish" },
	{ code: "da-DK", name: "Danish" },
	{ code: "fi-FI", name: "Finnish" },
	{ code: "nb-NO", name: "Norwegian" },
	{ code: "cs-CZ", name: "Czech" },
	{ code: "el-GR", name: "Greek" },
	{ code: "he-IL", name: "Hebrew" },
	{ code: "hu-HU", name: "Hungarian" },
	{ code: "id-ID", name: "Indonesian" },
	{ code: "ms-MY", name: "Malay" },
	{ code: "ro-RO", name: "Romanian" },
	{ code: "sk-SK", name: "Slovak" },
	{ code: "th-TH", name: "Thai" },
	{ code: "uk-UA", name: "Ukrainian" },
	{ code: "vi-VN", name: "Vietnamese" },
	{ code: "bg-BG", name: "Bulgarian" },
	{ code: "hr-HR", name: "Croatian" },
	{ code: "ca-ES", name: "Catalan" },
	{ code: "fil-PH", name: "Filipino" },
	{ code: "ta-IN", name: "Tamil" },
	{ code: "te-IN", name: "Telugu" },
	{ code: "fa-IR", name: "Persian" },
	{ code: "ur-PK", name: "Urdu" },
	{ code: "sr-RS", name: "Serbian" },
	{ code: "sl-SI", name: "Slovenian" },
	{ code: "lt-LT", name: "Lithuanian" },
	{ code: "lv-LV", name: "Latvian" },
	{ code: "et-EE", name: "Estonian" },
] as const;

export type Language = (typeof LANGUAGES)[number];
export type LanguageCode = Language["code"];
